name: MTS Suvadi Due Book Notifications

on:
  # Manual testing for now
  workflow_dispatch:

jobs:

  send-notifications:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Firebase Admin SDK
        run: |
          pip install firebase-admin

      - name: Send due book notifications
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          python scripts/send_due_notifications.py
